apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
  labels:
    app: javaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: jenkins123
        image: prevasishta98/javaapp:latest11
        ports:
        - containerPort: 5000
