
version: '2'
services:
  web:
       build:
               context: ./
               dockerfile: Dockerfile
       container_name: java_app
       volumes:
          - ./:/var/www/html/ 
       ports:
         - 8009:80
