apiVersion: v1
kind: Service
metadata:
  name: javaapp-service
spec:
  selector:
    app: javaapp
  ports:
    - protocol: TCP
      port: 5000  # External port exposed by the service
      targetPort: 5000  # Internal port in the container
  type: LoadBalancer  # Can also use NodePort or ClusterIP
