apiVersion: v1
kind: Service
metadata:
  name: javaapp-service
spec:
  selector:
    app: javaapp
  ports:
    - protocol: TCP
      port: 8083  # External port exposed by the service
      targetPort: 8083  # Internal port in the container
  type: Nodeport  # Can also use NodePort or ClusterIP
